### ISSUE TITLE
test.bin or test to kernel7.img?

### ISSUE THREAD

**Issue by sanderjo** [swarren/rpi-3-aarch64-demo#1]
Hi, thank you for your work!

The readme says:

> Copy test.bin to the boot partition as kernel7.img

Is it really be `test.bin`, not the file `test`? Reason: `test.bin` is not recognized as aarch64, but `test` is:

```
sander@haring:~/git/rpi-3-aarch64-demo$ file test
test: ELF 64-bit LSB  executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped

sander@haring:~/git/rpi-3-aarch64-demo$ file test.bin
test.bin: data
```

I have no Raspi3 at hand to test it, so I'm asking here.

FWIW: build process on my Ubuntu 14.04:

```

sander@haring:~/git/rpi-3-aarch64-demo$ ./build.sh 
./build.sh: line 7: aarch64-linux-gnu-gcc: command not found

sander@haring:~/git/rpi-3-aarch64-demo$ sudo apt-get install gcc-aarch64-linux-gnu

sander@haring:~/git/rpi-3-aarch64-demo$ ./build.sh 
```

**Comment by swarren** [comment]
Yes test.bin is correct; the VC FW loads raw binary files not ELF files. "file" can't identify raw binary files but can identify ELF files.

**Comment by sanderjo** [comment]
OK, all clear. Thank you.
