### ISSUE TITLE
Compilation error in main.c

### ISSUE THREAD

**Issue by sukantoghosh** [swarren/rpi-3-aarch64-demo#2]
I fixed (https://github.com/sukantoghosh/rpi-3-aarch64-demo/commit/03d941e30c178d15ba42c157bf80197c9ce40f74) the following compilation error in main.c when compiled with Linaro gcc 4.8.2 ($ aarch64-linux-gnu-gcc --version
aarch64-linux-gnu-gcc (crosstool-NG linaro-1.13.1-4.8-2013.08 - Linaro GCC 2013.08) 4.8.2 20130805 (prerelease))

```
+ aarch64-linux-gnu-gcc -c -o main.o main.c
main.c: In function ‘dbg_puthex32’:
main.c:77:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 28; i >= 0; i -= 4)
  ^
main.c:77:2: note: use option -std=c99 or -std=gnu99 to compile your code
```

**Comment by swarren** [comment]
This should be fixed by my latest push.
